services:
  api:
    build:
      context: ./PersonalFinanceApi
      dockerfile: Dockerfile
    container_name: personal-finance-api
    extra_hosts:
      - "dockerhost:host-gateway"
    environment:
      PORT: "8080"
      DisableHttpsRedirection: "true"
      ConnectionStrings__DefaultConnection: "Server=tcp:mssql-azure-pfa.database.windows.net,1433;Initial Catalog=PersonalFinanceDb;Persist Security Info=False;User ID=geobw30;Password=3N73ri2e-;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
      Cors__AllowedOrigins__0: "http://localhost:5173"
    ports:
      - "5254:8080"

  web:
    build:
      context: ./personal-finance-client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5254/api"
    container_name: personal-finance-web
    depends_on:
      - api
    environment:
      PORT: "4173"
    ports:
      - "5173:4173"
